#!/bin/sh

# To forward the logs to a graylog server & to log to the system
#exec /usr/bin/svloggelfd -H 127.0.0.1:12201 -s mongodb -e | svlogd -tt /var/log/mongodb
exec  svlogd  -tt  /var/log/mongodb
